### ISSUE TITLE
Collision geometry protrides out of the robot mesh

### ISSUE THREAD

**Issue by ggupta9777** [blackcoffeerobotics/bcr_bot#23]
![Screenshot from 2024-02-22 04-00-44](https://github.com/blackcoffeerobotics/bcr_bot/assets/13151010/bb922726-82fc-40b4-ac3d-7acf93757188)

We have used simplified collisions but they extend beyond robot body. They should align with the visual mesh, I think disabling self collision should do alongside updated wheel link positions

**Comment by ANGELOANTU7** [comment]
resolved the issue 

![Screenshot from 2024-03-13 10-48-17](https://github.com/blackcoffeerobotics/bcr_bot/assets/94218410/3ffbd555-0adf-4ebe-925b-fa84946c9245)
