### ISSUE TITLE
Isaac Sim USD File

### ISSUE THREAD

**Issue by cyhunblr** [blackcoffeerobotics/bcr_bot#47]
USD file from this repository probably wrong
![image](https://github.com/user-attachments/assets/4323160c-ab4e-48ea-abcc-c6b69b1d2073)

**Comment by Afritheos** [comment]
same here...

**Comment by D-1shu** [comment]
@KeneUkwueze @cyhunblr We are working on a fix it will be out by tomorrow. Thanks for reporting.

**Comment by cassiniR** [comment]
Import brc_bot.usd, press the play button, and the following error appears, which keeps refreshing. I think I need to change the prim of isaac_conpute_odometry_node.
![Uploading Snipaste_2024-11-13_10-17-25.jpg…]()

**Comment by cassiniR** [comment]
Import brc_bot.usd, press the play button, and the following error appears, which keeps refreshing. I think I need to change the prim of isaac_conpute_odometry_node.
![Snipaste_2024-11-13_10-17-25](https://github.com/user-attachments/assets/973409b4-3c5b-49b0-bde1-d4c16d8902be)

**Comment by D-1shu** [comment]
Hey @cassiniR, I can see the message but the Odom data is correct. You can verify. Also if you find a fix for removing the error logs, please submit a PR.

**Comment by ggupta9777** [comment]
Closing this issue since the robot is up and running and now.

**Comment by cyhunblr** [comment]
Thanks for your effort. By the way, how can we increase the IMU, LiDAR or Camera Hz values? 
For example, I want to set IMU to 200hz
